// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlvnrvwkvzxfnfozqtaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sdm5ydndrdnp4Zm5mb3pxdGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjU4OTEsImV4cCI6MjA2ODM0MTg5MX0.dGvVjY4tS7ayzMOZVCjlvvx0V4zwKeWhRy_p3-fGHoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});